{
  "type": "record",
  "name": "SeguimientoTrabajoCanceladoV1",
  "namespace": "seguimiento.eventos",
  "fields": [
    {
      "name": "event_id",
      "type": "string"
    },
    {
      "name": "tipo",
      "default": "SeguimientoTrabajoCancelado.v1",
      "type": "string"
    },
    {
      "name": "version_contrato",
      "default": 1,
      "type": "int"
    },
    {
      "name": "instante",
      "type": "string"
    },
    {
      "name": "correlacion",
      "type": "string"
    },
    {
      "name": "causacion",
      "type": "string"
    },
    {
      "name": "id_saga",
      "type": "string"
    },
    {
      "name": "id_solicitud",
      "type": "string"
    },
    {
      "name": "id_trabajo",
      "type": "string"
    },
    {
      "name": "id_partner",
      "type": "string"
    },
    {
      "name": "id_seguimiento",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "cancelado_en",
      "type": "string"
    }
  ]
}
